name: Linting

on:
  pull_request:
  push:
    paths:
      - .github/workflows/lint.yml
      - "**.sh"

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: ./stage2-musicbox/00-musicbox/files/.bashrc
